version: '3.4'

services:
  gateway.web:
    image: ${DOCKER_REGISTRY-}gateway.web
    container_name: gateway-container
    ports: 
      - "8010:80"
    build:
      context: .
      dockerfile: Gateway\DockerAPIS.GateWay.Web\Dockerfile

  contactsapi:
    image: ${DOCKER_REGISTRY-}contacts
    container_name: ContactsAPI
    hostname: contactsapi
    ports: 
      - "8011:80"
    build:
      context: .
      dockerfile: Services\Contact\Web\API\DockerAPIS.Services.Contact.Web.API\Dockerfile

  classroomapi:
    image: ${DOCKER_REGISTRY-}classroom
    container_name: ClassroomAPI
    hostname: classroomapi
    ports: 
      - "8012:80"
    build:
      context: .
      dockerfile: Services\Classroom\Web\API\DockerAPIS.Services.Classroom.Web.API\Dockerfile

  contactscache:
    image: redis
    container_name: ContactsCache
    command: --port 6380
    ports: 
      - "6380:6380"
    
  classroomcache:
    image: redis
    container_name: ClassroomCache
    command: --port 6377
    ports: 
      - "6377:6377"