version: '3.4'

services:
  contacts:
    image: ${DOCKER_REGISTRY-}contacts
    build:
      context: .
      dockerfile: Contacts\Dockerfile

  classroom:
    image: ${DOCKER_REGISTRY-}classroom
    build:
      context: .
      dockerfile: Classroom\Dockerfile

  ContactsCache:
    image: redis
    container_name: ContactsCache
    command: --port 6380
    expose:
      - "6380"
    ports: 
      - "6380:6380"
    
  ClassroomCache:
    image: redis
    container_name: ClassroomCache
    command: --port 6377
    expose:
      - "6377"
    ports: 
      - "6377:6377"