version: '3.4'

services:
  contacts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  classroom:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

