version: '3.4'

services:
  contactsapi:
    image: ${DOCKER_REGISTRY-}contacts
    container_name: ContactsAPI
    hostname: contactsapi
    build:
      context: .
      dockerfile: Contacts\Dockerfile

  classroomapi:
    image: ${DOCKER_REGISTRY-}classroom
    container_name: ClassroomAPI
    hostname: classroomapi
    build:
      context: .
      dockerfile: Classroom\Dockerfile

  contactscache:
    image: redis
    container_name: ContactsCache
    command: --port 6380
    ports: 
      - "6380:6380"
    
  classroomcache:
    image: redis
    container_name: ClassroomCache
    command: --port 6377
    ports: 
      - "6377:6377"