version: '3.4'

services:
  contactsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  classroomapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

